### ISSUE TITLE
What is the mongodb_meta index? How do I store the whole document in Elasticsearch? How many threads does Mongo Connector create?

### ISSUE THREAD

**Issue by avinashr** [10gen-labs/mongo-connector#154]
We are trying to evaluate MongoDB Connector for replicating data from MongoDB to elasticSearch. Below is the command we are using

  mongo-connector -m servername:27017  --namespace-set ns.coll1 -t http://localhost:9200/ --dest-namespace-set indexcoll1 --fields clientId,batchId  -d /Users/myuser/git/mongo-connector/mongo_connector/doc_managers/elastic_doc_manager.py

I noticed that when we run this , there is an index mongoDB_meta index that is getting created. Is there a significance for that index ?

Also how do we make sure that the complete document from MongoDB is getting stored in elasticsearch along with the index. Is there a setting or config i am missing

Currently only way to achieve that is by listing out all the fields with --fields argument? 

Also --fields argument does not allow us specify fields per collection? please confirm.

Elasticsearch:1.0.1
MongoDB:2.4.1

_source is enabled on the elasticsearch end.

**Comment by lovett89** [comment]
Closing this. This question is now part of the [FAQ](https://github.com/10gen-labs/mongo-connector/wiki/FAQ)
