### ISSUE TITLE
Support Auth in DocManagers

### ISSUE THREAD

**Issue by chicoandrade** [10gen-labs/mongo-connector#190]
Hi, I'm trying to use mongo-connector with two replica sets, but keep getting the following error:
...
File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 178, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
mongo_connector.errors.OperationFailed: command SON([('listDatabases', 1)]) failed: not authorized on admin to execute command { listDatabases: 1 }

Here is the command-line for the execution:
mongo-connector -m suba-mongodb-temp-01:27013 -t suba-mongodb-temp-01:27003 -d ./mongo_doc_manager.py --password-file ./mongodb.key

The specified user connects in the two instances and can perform an "show dbs" command.
Im using the version 1.3.

**Comment by llvtt** [comment]
Mongo Connector 2.1 supports providing arbitrary keyword arguments to the constructors of clients within a DocManager. That should wrap up any other requirements for providing credentials or SSL certificates to the underlying clients.
