### ISSUE TITLE
Question: How to index multiple collections at a time with --namespace-set and --dest-namespace-set

### ISSUE THREAD

**Issue by tandasima** [10gen-labs/mongo-connector#210]
Hello,

My collections start with an uppercase letter. To index a single collection, I use the command below and it works well.

mongo-connector -m localhost:27017 -t localhost:9202 --namespace-set Colegio.conversations --dest-namespace-set colegio.conversations -d /Library/Python/2.7/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py

Problem:
How should I rewrite it if I want to index more than one collection at one time?

Thanks

**Comment by lovett89** [comment]
@tandasima 
You can list multiple collections separated by a comma to `--namespace-set`. Same goes for `--dest-namespace-set`. Each name given to `--namespace-set` is mapped respectively to the name in `--dest-namespace-set`:

    mongo-connector --namespace-set db1.collection1,db2.collection2 \
                    --dest-namespace-set newdb1.newcollection1,newdb2.newcollection2

In this example, `db1.collection1` will become `newdb1.newcollection1`, and `db2.collection2` will become `newdb2.newcollection2` once it gets to Elasticsearch.

**Comment by tandasima** [comment]
Worked. Thank you.
