### ISSUE TITLE
Using the -i option only stores data in _source and does not index...

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#221]
Hi,

When I use the -i option in the command line argument, Elasticsearch only stores this field in the _source field, however it's not searchable or indexed. How do I select only certain fields to index them and mke them searchable (whether or not it stores them in _source)?

Thanks,
Ben.

**Comment by llvtt** [comment]
Mongo Connector only ever updates the source document in Elasticsearch (and thus causes a dynamic mapping to be created on the first insert, if no mapping type exists already). What fields are indexed are determined by the mapping, which can be set on Elasticsearch itself: http://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-core-types.html. Usually, all fields are indexed by default. Perhaps you have a different default mapping set up?

**Comment by bdesilva** [comment]
Well here is my default mapping:

PUT myIndex
{
  "settings": {
    "number_of_shards": 6,
    "number_of_replicas": 2
  },
  "mappings": {
    "contact": {
      "dynamic" : true,
      "properties": {
        "firstName": {
          "ignore_malformed": true, 
          "type": "string",
          "index": "not_analyzed"
        }
      }
    }
  }
}

**Comment by llvtt** [comment]
Not sure what's going on here. This worked for me:

1. Add mapping definition in Elasticsearch:

        curl -XPUT :9200/estest -d'{
          "mappings": {
            "mapping_test": {
              "dynamic": true,
              "properties": {
                "name": {
                  "type": "string",
                  "index": "not_analyzed",
                  "ignore_malformed": true
                }
              }
            }
          }
        }'

2. Start `mongo-connector`:

        mongo-connector -t localhost:9200 -d elastic_doc_manager -n estest.mapping_test

3. Insert documents into MongoDB:

        use estest
        db.mapping_test.insert({"name": "elmo"})
        db.mapping_test.insert({"name": "grover"})

4. Query Elasticsearch:

        $ curl -XGET :9200/estest/mapping_test/_search -d'{
          "query": {
            "match": {"name": "elmo"}
          }
        }'

    output:

        {
            "_shards": {
                "failed": 0,
                "successful": 5,
                "total": 5
            },
            "hits": {
                "hits": [
                    {
                        "_id": "5509df6e827f6546b33b41df",
                        "_index": "estest",
                        "_score": 1.0,
                        "_source": {
                            "name": "elmo"
                        },
                        "_type": "mapping_test"
                    }
                ],
                "max_score": 1.0,
                "total": 1
            },
            "timed_out": false,
            "took": 23
        }

   This time using `term` instead of `match`:

        $ curl -XGET :9200/estest/mapping_test/_search -d'{
          "query": {
            "term": {"name": "elmo"}
          }
        }'

    output:

        {
            "_shards": {
                "failed": 0,
                "successful": 5,
                "total": 5
            },
            "hits": {
                "hits": [
                    {
                        "_id": "5509df6e827f6546b33b41df",
                        "_index": "estest",
                        "_score": 1.0,
                        "_source": {
                            "name": "elmo"
                        },
                        "_type": "mapping_test"
                    }
                ],
                "max_score": 1.0,
                "total": 1
            },
            "timed_out": false,
            "took": 3
        }

Some things to check:
1. Since `firstName` is `not_analyzed`, only an exact match will return the document. Are you sure that there is no disparity in letter case, extra whitespace, etc. in your query?
2. What `index` ever set to anything else (such as `no`) in the mapping type for `firstName`? If so, you will have to re-index these documents to get the effect of `not_analyzed`.

**Comment by llvtt** [comment]
I'm closing this issue since it hasn't been active in awhile. Please feel free to reopen this if there's more to discuss.
