### ISSUE TITLE
Mapping exception from Mongo ISO Date...

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#223]
Hi,

I'm using mongo-connector version 2.x and I'm getting a mapping exception in accordance with some fields I have using Mongo date formats. I'm trying to use a mapping in Elasticsearch to set these fields to an Elasticsearch date format otherwise to ignore malformed fields.

Does anyone have any information about this?

Thanks,
Ben.

**Comment by llvtt** [comment]
@bdesilva 
Could you please provide:
- The Exception and stacktrace
- The command you're using to run mongo-connector
- The mapping you've set up in Elasticsearch

**Comment by bdesilva** [comment]
Hi, here is the exception for the date mapping issue:

Could not bulk-upsert document into ElasticSearch: {u'index': {u'status': 400, u'_type': u'contacts', u'_id': u'someFieldIdString', u'error': u'MapperParsingException[failed to parse...

However, I'm also experiencing NumberFormatExceptions as follows:

2015-03-17 17:17:10,920 [ERROR] mongo_connector.doc_managers.elastic_doc_manager:193 - Could not bulk-upsert document into ElasticSearch: {u'index': {u'status': 400, u'_type': u'contacts', u'_id': u'someFieldIdString', u'error': u'MapperParsingException[failed to parse [fieldInQuestion]]; nested: NumberFormatException[For input string: "2.5"]; ', u'_index': u'contacts'}}

Here is the current command I use to run the mongo-connector:

mongo-connector -m mongo-wired-tiger-server:27017 -t elasticsearch-server:9200 -d elastic_doc_manager -n database.collection -g index.type

Here is the current mapping I use:

PUT contacts
{
  "settings": {
    "number_of_shards": 6,
    "number_of_replicas": 2
  },
  "mappings": {
    "contact": {
      "dynamic" : true,
      "properties": {
        "firstName": {
          "ignore_malformed": true, 
          "type": "string",
          "index": "not_analyzed"
        },
        "lastName": {
          "ignore_malformed": true, 
          "type": "string",
          "index": "not_analyzed"
        },
        "address": {
          "ignore_malformed": true, 
          "type": "string",
          "index": "not_analyzed"
        },
        "newField": {
          "ignore_malformed": true, 
          "type": "object",
          "index": "not_analyzed",
          "properties": {
            "source_date_time": {
              "ignore_malformed": true, 
              "type": "date",
              "index": "not_analyzed"
            }
          }
        },
        "createdDate": {
          "ignore_malformed": true, 
          "type": "date",
          "index": "not_analyzed"
        },
        "modifiedDate": {
          "ignore_malformed": true, 
          "type": "date",
          "index": "not_analyzed"
        }
      }
    }
  }
}

Also to note that my mongo server is using the new wired-tiger technology for compression which shouldn't affect mongo-connector since the data should be uncompressed by the time the mongo-connector gets the data.

I left the mongo-connector running for a few horus as there are about 385GB worth of data to be indexed into Elasticsearch, however after signing in, Elasticsearch had crashed with this error reported on the mongo-connector log:

ReadTimeoutError: HTTPConnectionPool(host=u’elasticsearch-server', port=9200): Read timed out. (read timeout=10)
2015-03-17 17:17:25,777 [ERROR] mongo_connector.oplog_manager:546 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient([u’mongo-replica1:27017', u’mongo-replica2:27017', u’mongo-replica3:27017']), u'local'), u'oplog.rs')
2015-03-17 17:17:25,995 [ERROR] mongo_connector.connector:301 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140604607993600)> unexpectedly stopped! Shutting down
2015-03-17 17:17:25,995 [INFO] mongo_connector.connector:356 - MongoConnector: Stopping all OplogThreads

I think this may have to do with the vast number of NumberFormatExceptions because the Elasticsearch server seemed to have crashed shortly after.

I was thinking to get through the NumberFormatExceptions by mapping those affected fields in Elasticsearch again, however is there a way that the mongo connector can handle this?

Thanks for your help.

**Comment by llvtt** [comment]
@bdesilva 
If the Elasticsearch server was crashing while mongo-connector was attempting to read from it (as it does when applying updates), then `ReadTimeoutError` probably makes sense here. Possibly the Elasticsearch Python driver may also be doing some reads on the Elasticsearch server beyond what mongo-connector controls as well.

Mongo Connector does not make any attempt to define a mapping beyond the dynamic mapping automatically created by Elasticsearch when the first document is inserted. Thus, if you want to define special types or formats for fields in a mapping, this needs to be done manually on Elasticsearch before indexing documents with Mongo Connector.

**Comment by bdesilva** [comment]
Thanks @llvtt for your help, yeah I had to refine my Elasticsearch instance by doing the following:

1) Set my index refresh interval to -1 in order to turn off index refreshing.
2) Set my replica shards to zero in order for replication to not occur during indexing.
3) Set my primary shards to an (n - 1) basis where n = number of nodes. So I have one node free that I can increase my replicas to and this did the job where the data import is working well. :)

I would like it to be faster as it takes about two weeks or so to import the 600GB, but I'm very happy that everything is going well with the import. :)

I really appreciate your help in all these questions as you've really helped me with my architecture. The only question I have now is how to turn off mongo connector logging or keep the logging down to only the latest entries because the space on my mongo connector server is not that much. I opened another question for this so I would really like your help on that.

Thanks,
Ben.

**Comment by llvtt** [comment]
Our discussion on logging configuration is over on #227, so I'll close this issue. Feel free to reopen if you think there's more to discuss here.

**Comment by philb89** [comment]
Hi llvtt,
when i run mongo-connector to index data to elastic search server, i get error like the image:
....
elasticsearch numberformatexception for input string 2015-02-02T21:25:35.442Z...
... could you help me? 
i use elastic search 1.7.0, mongodb 2.6
![elasticsearch](https://cloud.githubusercontent.com/assets/13758592/9215806/c7e0c39c-40d9-11e5-96ca-c4b80b1a0da9.png)

**Comment by llvtt** [comment]
@philb89 It looks like Elasticsearch is trying to parse a Number out of a Date string. You probably have a mismatch between your MongoDB document structure and your Elasticsearch mapping definition.

**Comment by philb89** [comment]
thanks @llvtt 
let me try this :)
