### ISSUE TITLE
ReadTimeoutError: HTTPConnectionPool (read timeout=10) - how to increase Elasticsearch read timeout from Mongo Connector?

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#225]
Hi, 

I'm doing a huge data import from Mongo db (collection size is approx. 385GB) via the mongo connector to be indexed into Elasticsearch. I keep getting this error: ReadTimeoutError: HTTPConnectionPool (read timeout=10), and I understand that I have to increase the read timeout value from an Elasticsearch client in order to fix this, unless there's another way to fix this? How would I change the read time out from Mongo Connector?

Thanks,
Ben.

**Comment by llvtt** [comment]
@bdesilva 
This isn't configurable right now, but I can make a change so that arbitrary options can be set on the Elasticsearch Python driver. For now, what you can do is add a `timeout` parameter to [this line](https://github.com/10gen-labs/mongo-connector/blob/master/mongo_connector/doc_managers/elastic_doc_manager.py#L58) in `elastic_doc_manager.py` like this:

    self.elastic = Elasticsearch(hosts=[url], timeout=XXX)

However, the default 10 second timeout is quite a lot already... perhaps the `ReadTimeoutError` is indicative of some other problem with the Elasticsearch setup?

**Comment by bdesilva** [comment]
@llvtt Thanks very much, I'll try that option a a last resort. I did some digging around on indexing tuning and what seemed to work for me is to alter my mapping to reduce any replica shards to 0 and to disable the index refresh rate thereby allowing more resources for indexing.

**Comment by jackbbhua** [comment]
hi,i install mongo connector via pip install mongo-connector.
now i want change elastic_doc_manager.py but i can not find where this file local at.please help.

**Comment by llvtt** [comment]
@jackbbhua Please create a separate issue for each problem, unless you think your issue may be the same as one already filed on Github. `elasticsearch_doc_manager.py` is under `mongo_connector/doc_managers`, which lives in your Python's `site-packages` directory.

This issue, as it relates to read timeout in Elasticsearch, looks complete. If there's more to discuss here, please feel free to reopen. @jackbbhua, if you need any more assistance, please create another issue.

**Comment by devinrsmith** [comment]
It would be nice if this were easily configurable.

**Comment by llvtt** [comment]
@devinrsmith @bdesilva 

As of [this commit](f419805e9d86f62b890ada219923a444573851d5), arbitrary parameters can be passed to the underlying clients in the doc managers. For instance, in your config file:

```json
"docManagers": [
  {
    "docManager": "elastic_doc_manager",
    "targetURL": "localhost:9200",
    "args": {
      "clientOptions": {
        "timeout": 100
      }
    }
  }
]
```

**Comment by devinrsmith** [comment]
Perfect!

**Comment by axelsoto** [comment]
I'm sorry but I couldn't find this config file. Where can I find it?

**Comment by rahulkamath91** [comment]
@axelsoto https://github.com/mongodb-labs/mongo-connector/blob/master/config.json
