### ISSUE TITLE
Can I disable the mongo-connector.log?

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#227]
Hi,

The mongo-connector log is very large, can I please disable this? Also, is there is a way to point this to some other server for logging or compressing the log, etc...?

Thanks,
Ben.

**Comment by llvtt** [comment]
Please have a look at the [logging configuration options](https://github.com/10gen-labs/mongo-connector/wiki/Configuration%20Options#configure-logging).

**Comment by bdesilva** [comment]
@llvtt Thanks, but there' no way to disable it in those logging options unless I'm missing something?

**Comment by llvtt** [comment]
There isn't a way to turn off logging completely, but that's probably a good thing. If something goes wrong, you'll want to have at least some logs handy to help diagnose what happened.

If you want to keep around less of the log, you can decrease the rotation interval and lower the "rotation when" value. For example, you can rotate the log file every 6 hours and keep only the latest one, if you so choose. These options are all documented in the page I linked to in my previous comment.

**Comment by llvtt** [comment]
Linking issue #234. It would be nice to have finer-grained verbosity control.

**Comment by llvtt** [comment]
Finer-grained verbosity control is implemented, so I'm closing this issue. Feel free to reopen if there's more to discuss.
