### ISSUE TITLE
tz-aware option not working

### ISSUE THREAD

**Issue by heichwald** [10gen-labs/mongo-connector#228]
Hello, I tried the following:
```
 mongo-connector --main localhost  --target-url http://localhost:9200 --namespace-set articles.articles --dest-namespace-set articles_v6.articles --doc-manager elastic_doc_manager  --tz-aware

or

 mongo-connector --main localhost  --target-url http://localhost:9200 --namespace-set articles.articles --dest-namespace-set articles_v6.articles --doc-manager elastic_doc_manager  --tz-aware true
```

It seems that the option does not work as it does get indexed incorrectly in elastic

in `connector.py`
```
# Timezone awareness
 self.tz_aware = kwargs.get('tz_aware', False)
print kwargs
```
outputs
```
{'ssl_ca_certs': None, 'ssl_certfile': None, 'fields': [], 'ns_set': ['articles.articles'], 'dest_mapping': {'articles.articles': 'articles_v6.articles'}, 'ssl_cert_reqs': None, 'batch_size': -1, 'gridfs_set': [], 'ssl_keyfile': None, 'continue_on_error': False, 'collection_dump': True}
```

```
pip show mongo-connector
---
Name: mongo-connector
Version: 2.0.1
Location: /Library/Python/2.7/site-packages
Requires: pymongo, elasticsearch, pysolr
```

**Comment by llvtt** [comment]
Thanks for the detailed report! This should be fixed in master now.

**Comment by llvtt** [comment]
If this does work for you, I'll close this issue after I add more detailed testing around the config file and command-line options.

**Comment by heichwald** [comment]
Yes this works, thanks

**Comment by heichwald** [comment]
BTW, how do you handle releases, when can we expect a 2.02 with this in it?

Thanks

**Comment by llvtt** [comment]
I'll be releasing a 2.0.2 version soon with this fix in it (probably early next week). I just need to finish writing more tests around this, first.

As to your second question, there isn't a way to access that from the command-line, but you can set arbitrary options on a DocManager from the config file. For example:

```
{
  ...
  "docManagers": [
    {
      "docManager": "elastic_doc_manager",
      "targetURL": "localhost:9200",
      "args": {"chunk_size": <chunk size here>}
    }
  ]
  ...
}
```

**Comment by heichwald** [comment]
Hi Luke,

any news on 2.0.2?
Just to know if I wait for it or if I do a workaround in an older version for now.

Thanls

**Comment by llvtt** [comment]
@heichwald 
Just uploaded to pypi: https://pypi.python.org/pypi/mongo-connector

**Comment by heichwald** [comment]
Thanks
