### ISSUE TITLE
Doc missing information for writing own connector

### ISSUE THREAD

**Issue by heichwald** [10gen-labs/mongo-connector#230]
Why do we have update method in this file:

 https://github.com/10gen-labs/mongo-connector/blob/master/mongo_connector/doc_managers/elastic_doc_manager.py#L114 

while it is not mentioned here:

https://github.com/10gen-labs/mongo-connector/wiki/Writing%20Your%20Own%20DocManager

**Comment by llvtt** [comment]
Thanks for pointing that out! Fixed.
