### ISSUE TITLE
Can I run many instances to watch two collections or is one query pointing to two collections enough?

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#231]
Hi,

If I start one instance of the mongo connector with this statement:

mongo-connector -m mongo-replica-server:27017 -t elasticsearch-server:9200 -d elastic_doc_manager -n myDb.names,myDb.contacts -g names.name,contacts.contact

Will it automatically sync to my named Elasticsearch indexes from both collections, so for example, after the initial collection dump, if records are inserted in batches (ie: 100 names per second and 200 contacts per 10s), will mongo connector capture these requests and index them automatically to the respective Elasticsearch indexes (names.name and contacts.contact), or do I have to open two separate mongo connector instances against the same server (where the mongo connector is installed), and run these two separate statements:

mongo-connector -m mongo-replica-server:27017 -t elasticsearch-server:9200 -d elastic_doc_manager -n myDb.names -g names.name

mongo-connector -m mongo-replica-server:27017 -t elasticsearch-server:9200 -d elastic_doc_manager -n myDb.contacts -g contacts.contact

Thanks,
Ben.

**Comment by llvtt** [comment]
A single instance of `mongo-connector` can do both indexes.

**Comment by bdesilva** [comment]
Thanks @llvtt, and just for my information, if I did open two separate instances, would that mess up the first instance or would that still work?

**Comment by llvtt** [comment]
It's safe to run separate instances of `mongo-connector` as long as 
they're operating on mutually exclusive namespaces:

safe:

     mongo-connector -n A -g X
     mongo-connector -n B -g Y

not safe:

     mongo-connector -n A -g X
     mongo-connector -n A -g Y

not safe:

     mongo-connector -n A -g X
     mongo-connector -n B -g X

Also, make sure you're using different `--oplog-ts` files. You should 
also make sure to keep their log files separate as well.

**Comment by bdesilva** [comment]
Ahh I understand, so basically as long as the collections are on separate mongo databases and don't have same index names, two instances work well.

Thanks!

**Comment by llvtt** [comment]
This discussion seems complete, so I'll close this issue. Feel free to reopen if you think there's more to discuss.
