### ISSUE TITLE
Running mongo-connector as a Linux service...

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#235]
Hi,

Is it possible to run the mongo-connector as a Linux service similar to how mongo runs? This is because using Putty to remote into a virtual machine that's always on almost always has disconnection software issues with Putty and I have to restart the mongo-connector.

Please let me know if this is possible.

Thanks,
Ben.

**Comment by llvtt** [comment]
@bdesilva 
To install Mongo Connector as a linux service:

1. Edit [`config.json`](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options) to your liking.
2. Do `python setup.py install_service`.

This creates a "mongo-connector" entry in /etc/init.d and copies the "config.json" file to /etc/mongo-connector.json. This has been tested so far on Fedora, Debian, and CentOS but should work on similar systems.

To remove the service, do `python setup.py uninstall_service`. This removes all the files I just mentioned.

**Comment by llvtt** [comment]
Added this info to the wiki: https://github.com/10gen-labs/mongo-connector/wiki/Installation#installing-as-a-linux-service, since it seems generally useful.

**Comment by bdesilva** [comment]
Thanks, that sounds good, however I didn't find a json element for target Elasticsearch host. So in otherwords, how can I put my command line: 

mongo-connector -m my-mongo-server:27017 -t my-elasticsearch-server:9200 -d elastic_doc_manager -n db.contacts,db.addresses -g contacts.contact,addresses.address --continue-on-error

into the JSON config file? Since I have to create the config.json file in my base mongo-connector directory, what would my config.JSON look like given my command line since I can't run the command line arguments as my service parameters.

Thanks.

**Comment by llvtt** [comment]
The config file is extensively documented on the [Configuration Options](https://github.com/10gen-labs/mongo-connector/wiki/Configuration%20Options) page of the wiki and also in the example config file itself ("config.json"). Configuring what DocManager to use is documented here: https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#configure-docmanagers

**Comment by bdesilva** [comment]
Thanks, Got it! I missed the -t equivalent in the docManagers section. :)

**Comment by bdesilva** [comment]
Hi, I tried installing and running the service, but I keep getting this error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/connector.py", line 259, in run
    self.address, tz_aware=self.tz_aware, **self.ssl_kwargs)
  File "/usr/lib64/python2.6/site-packages/pymongo/mongo_client.py", line 369, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: [Errno 111] Connection refused

Why is that?

**Comment by bdesilva** [comment]
And I'd like to add that I'm using CentOS 6.

Thanks.

**Comment by llvtt** [comment]
It looks like the init script is working, since mongo-connector attempted to start. MongoDB may have refused the connection for a number of reasons, including that it may not be running at all. This is outside the scope of the Github issue tracker, so I'd recommend attempting to debug this a bit more on your own, then possibly post a question on the mongodb-user Google group if you're still having trouble.

Closing this issue, since it looks like you've got mongo-connector running as a Linux service.

**Comment by bdesilva** [comment]
Hi, thanks for your advice. I did the install but I still get this error when I do a service --status-all: mongo-connector /etc/init.d/mongo-connector: line 81: status_of_proc: command not found

I will check with the mongo community as well, however I'm not sure where to start in order to debug this because the mongo-connector code is a bit of a black box to me at the moment. I will have to take a look into the code because I really do need this running as a service.
