### ISSUE TITLE
[Reignfire] observer: timeout notification from cluster service. timeout setting [1m], time since start [59.9s]

### ISSUE THREAD

**Issue by jackbbhua** [10gen-labs/mongo-connector#236]
[Reignfire] observer: timeout notification from cluster service. timeout setting [1m], time since start [59.9s]

what is this error mean and how to config?thanks

**Comment by jackbbhua** [comment]
this is the error form elasticseach log:


[2015-03-25 16:09:22,192][DEBUG][action.index             ] [Dominus] observer: timeout notification from cluster service. timeout setting [1m], time since start [59.9s]

**Comment by llvtt** [comment]
This question would better be directed at the [Elasticsearch Google Group](https://groups.google.com/forum/#!forum/elasticsearch). This bug tracker is only for Mongo Connector issues.
