### ISSUE TITLE
Custom command line parameters

### ISSUE THREAD

**Issue by heichwald** [10gen-labs/mongo-connector#237]
Hello, 

it would be nice if we would have some way to pass additional custom configuration to the DocManager via the command line.

**Comment by llvtt** [comment]
This is possible with the config file: https://github.com/10gen-labs/mongo-connector/wiki/Configuration%20Options#docmanagersindexargs. The reason this isn't also a command-line option is that specifying which doc managers get which arguments would be very awkward syntactically.

**Comment by heichwald** [comment]
Right , I did not think about the multiple doc managers possibility.
thanks
