### ISSUE TITLE
Index Names in Elastic Search Changed?

### ISSUE THREAD

**Issue by thelok** [10gen-labs/mongo-connector#239]
I'm upgrading from 1.3.1 to 2.0.1 and I noticed that the index names are now different when being put into elastic search? For example when I would expect elastic search to have the index called "example.somecollection" I would instead get an index called "example" with a "_type" field of "somecollection". I don't see anything in the changelog that says this should have changed.

Did something change? I've even tried to manually do the index mappings using the -g option but it seems to still split the index on the dot "."

**Comment by thelok** [comment]
Nevermind... I see the commit where this change was made.

https://github.com/10gen-labs/mongo-connector/commit/aeb9ef89a6ccd2533b71a836b5ca6c9eac104cb6

Doesn't look like there's backwards compatibility with this. I was using specific indexes to configure different sharding strategies.

**Comment by jaredkipe** [comment]
I also wish that the old pattern stayed, or was accessible somehow through a cli flag.  The new way means that even with index aliases, all 'fields' are visible for all aliases which is very confusing to users in Kibana.

**Comment by llvtt** [comment]
The new behavior for how MongoDB databases and collections are used in Elasticsearch is described in the [wiki](https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20ElasticSearch#elasticsearch-indexes-mappings-and-types). It's also worth noting that the index and mapping type are chosen after the [namespace mapping](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#namespacesmapping), so you can funnel each collection into its own index by renaming it.

**Comment by jaredkipe** [comment]
I did notice/read about the new default behavior.

Unfortunately for me, I did not know that namespace mapping could be used to implement a 1 collection to 1 index mapping.  I still don't actually.

Could you describe how to 'comma separated list of new names' as an example?
e.g. if I have a db with col1, col2, col3 and I only want col1 and col2 (not col3) and I want them to be their own index, ideally named 'col1' and 'col2' (though db.col1 would be acceptable) how would I accomplish this?

**Comment by thelok** [comment]
The best I would be able to do to achieve the old pattern is something like:

"example_somecollection.string" where it would have an index of "example_somecollection" and the type of "string"

Unless you're thinking of something else?

**Comment by jaredkipe** [comment]
I tried changing "namespace" in config.json (perhaps I didn't make it use this file?) to something like this, but it didn't work.
I'm probably using it wrong.

```
"namespaces": {
        "include": ["db.col1", "db.col2"],
        "mapping": {
            "db.col1": "col1",
            "db.col2": "col2"
        },
        "__gridfs": ["db.fs"]
    }
```

**Comment by llvtt** [comment]
@thelok That's what I mean. If you have collections `A.x` and `A.y` (both `x` and `y` are in the `A` database and will therefore be put into the `A` index in Elasticsearch), you can force these collections to go into their own indexes like this:

    mongo-connector --namespace-set A.x,A.y --dest-namespace-set A_x.sometype,A_y.anothertype

Now `A.x` and `A.y` go into the `A_x` and `A_y` indexes, respectively, instead of into the same index with different types.

@jaredkipe Your config looks correct, except that `namespace.mapping` should have values that look like `database.collection`, e.g.:

    "include": ["db.col1", "db.col2"],
    "mapping": {
       "db.col1": "index.type",
       "db.col2": "index2.type"
    }

**Comment by jaredkipe** [comment]
OK, this is very helpful.  Also note that https://github.com/10gen-labs/mongo-connector/wiki/Configuration%20Options does not state that -c ./config.json is how you would load that config file.

Lets say that we have a database named 'magento' with a couple of collections like 'orders' and 'order_items'.  This works wonderfully

```
"namespaces": {
        "include": ["magento.orders", "magento.order_items"],
        "mapping": {
            "magento.orders": "orders.order",
            "magento.order_items": "order_items.order_item"
        }
    }
```

Then you can define templates for indexes named "orders" with mappings for "order" like so.
```
curl -XPUT localhost:9200/_template/template_1 -d '
{
    "template" : "orders",
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "order" : {
            "dynamic" : true,
            "enabled" : true,
            "_source" : { "enabled" : true },
            "properties" : {
              "user" : { 
                "type" : "string",
                "fields" : {
                  "raw": { "type" : "string", "index" : "not_analyzed" }
                }
              },
              "channel" : { 
                "type" : "string",
                "fields" : {
                  "raw": { "type" : "string", "index" : "not_analyzed" }
                }
              }
            }
        }
    }
}
'
```

**Comment by jaredkipe** [comment]
I think this can be closed now.  Thanks!
