### ISSUE TITLE
can i use mongo-connector to synchronous data from mongodb to elasticsearch?

### ISSUE THREAD

**Issue by helegehe** [10gen-labs/mongo-connector#245]
I got mongodb replica set ready on localhost:50000 and Elastic search on localhost:9200,and i have installed mongo-connector correctly in windows,how can i use it to dump data from mongodb into elasticsearch system?I have tried:
 mongo-connector -m localhost:50000 -t localhost:9200 -d mongo_doc_manager.py
but it didn't work:Could not import mongo_connector.doc_managers.mongo_doc_manager.py.
I do not know what is mongo_doc_manager.py?

**Comment by helegehe** [comment]
I also tried:
 mongo-connector -m localhost:50000 -t localhost:9200 -d elastic_doc_manager.py
and it still throwed exception:
Could not import mongo_connector.doc_managers.elastic_doc_manager.py

**Comment by behackett** [comment]
Please see the documentation for usage with elastic search here:

https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20ElasticSearch

**Comment by helegehe** [comment]
Thanks.I followed the document this time ,there is no exception,but nothing happened.It  just says:
Logging to mongo-connector.log.
I  can not find the data dumped from MongoDB,I am not sure whether it is succeed or not.

**Comment by llvtt** [comment]
@helegehe Try looking in mongo-connector.log (you can also increase the [verbosity](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#verbosity) if you want more detail).

**Comment by llvtt** [comment]
There hasn't been any activity in awhile on this ticket, so I'm going to close it. Feel free to reopen or create another issue if you have further questions or problems.

**Comment by DivyashreeLakkegowda** [comment]
I followed the same link to integrate mongo DB with elastic search.
https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20ElasticSearch
connected using command mongo-connector -m localhost:27017 -t localhost:9200 -d elastic_doc_manager.
it is showing Logging to mongo-connector.log.
but no data dumped from mongodb to elastic search

**Comment by llvtt** [comment]
@DivyashreeLakkegowda Please create a new issue and include output from mongo-connector.log.

**Comment by DivyashreeLakkegowda** [comment]
• How to customize the data flow between mongodb and elastic based on collection and columns?

**Comment by zerubeus** [comment]
I have the same problem after using the commend `mongo-connector -m ....` it just get stuck at `Logging to mongo-connector.log`
