### ISSUE TITLE
Existing data replication

### ISSUE THREAD

**Issue by slaniado** [10gen-labs/mongo-connector#246]
Hi, the connector is working fine, but I realized that if the service of the connector fails and i enter new data in mongodb and i restart the service the already data is not sync, is there a option to tell the connector to sync the existing data?

**Comment by llvtt** [comment]
Usually, mongo connector syncs only new data, based on the timestamp 
file (usually called "oplog.timestamp"). If you delete this file or use 
a new one, mongo-connector will sync everything from the beginning. See 
https://github.com/10gen-labs/mongo-connector/wiki/Oplog-Progress-File#collection-dumps-and-the-oplog-progress-file.

**Comment by llvtt** [comment]
I added this question to the FAQ. Closing this issue now; please feel free to reopen or create another issue if there's more to discuss.

**Comment by slaniado** [comment]
Thank you for your time 

Enviado desde mi iPhone
