### ISSUE TITLE
Does Mongo Connector supports for MongDB 3.0

### ISSUE THREAD

**Issue by tottishi05** [10gen-labs/mongo-connector#252]
I checked mongo connector wiki but didn't find the version compatibility. Does Mongo Connector supports for MongoDB 3.0??
If not, which is the latest verion of MongoDB supported by Mongo Connector?

**Comment by llvtt** [comment]
`mongo-connector` works with MongoDB 3.0.x and all versions of MongoDB down to 2.4 (and probably lower than that...). I'll add this to the FAQ.

**Comment by llvtt** [comment]
This has been added to the FAQ.
