### ISSUE TITLE
Luke admin url - 404 Not Found with Solr 5

### ISSUE THREAD

**Issue by fabricecetic** [10gen-labs/mongo-connector#262]
Hello,

Does this connector work with Solr 5 ? I get an error when running the mongo-connector command because the Luke request handler (i.e. admin/luke?show=schema&wt=json) cannot be found.

'''
...
declared_fields = self.solr._send_request('get', ADMIN_URL)
  File "/usr/local/lib/python2.7/dist-packages/pysolr.py", line 331, in _send_request
    raise SolrError(error_message)
mongo_connector.errors.OperationFailed: [Reason: Error 404 Not Found]
'''

Do you know how to install it (or any other document manager) with Solr 5 ? 

Thank you for your help,

**Comment by isank** [comment]
http://stackoverflow.com/questions/28398644/how-do-i-query-via-url-the-solr-admin-lukerequesthandler-to-get-collection-ind

**Comment by llvtt** [comment]
@fabricecetic Did you get what you needed? Is it ok if I close this issue?

**Comment by fabricecetic** [comment]
Yes, I finally found a solution writing my own Solr5 document manager where I append the name of the index in the url (in the constructor of the DocManager class):

```
self.url = url+'/my_index'
````

Thank you for your help,

**Comment by jonathanmeier5** [comment]
I am encountering a similar problem. fabricecetic, would you be willing to explain your solution to me in further detail?
