### ISSUE TITLE
mongo_doc_manager: update should update metadata-doc

### ISSUE THREAD

**Issue by XDestination** [10gen-labs/mongo-connector#283]

**Comment by llvtt** [comment]
Can you provide any more details? I'm not sure how to interpret the title of this issue.

**Comment by XDestination** [comment]
No problem. I was just looking through the provided doc_managers and for me it looks like that in the elastic doc_manager the metadata-document (_id,ns,_ts - in case of the mongo_doc_manager stored in the __mongo_connector database) is updated for upsert, update, bulk and remove operations. And in the case of the mongo_doc_manager i don't see the update of this document in the update function.

I would expect sth like

self.mongo["__mongo_connector"][namespace].save({
            '_id': doc['_id'],
            "_ts": timestamp,
            "ns": namespace
        })

there.

**Comment by llvtt** [comment]
Good point. Would you like to make a pull request to add this?

**Comment by XDestination** [comment]
Sure
