### ISSUE TITLE
Problem updating solr documents

### ISSUE THREAD

**Issue by rmarinvsn** [10gen-labs/mongo-connector#284]
Hi,

First of all, I think the idea of mongo-connector is just great, thanks for invest your time on this.

Now, I have a problem: mongo-connector shows an error when I try to update an existing document . I installed mongo-connector with pip, so I guess I have the latest version . When I insert or delete documents in Mongo, mongo-connector works just fine, but when I try to update an existing document, the command line window that is running mongo-connector shows:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\mongo_connector\util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "C:\Python34\lib\site-packages\mongo_connector\oplog_manager.py", line 263, in run
    ns, timestamp)
  File "C:\Python34\lib\site-packages\mongo_connector\util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "C:\Python34\lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py", line 246, in update
    doc.pop('ns')
KeyError: 'ns'

I need to force a resynch (deleting oplog.timestamp and restarting) to recover the system. 

What am I doing wrong?

Best,
Raúl

**Comment by llvtt** [comment]
Hi Raul,

Can you please provide the following:
- Log output from mongo-connector
- The command used to run mongo-connector

Thanks!

**Comment by rmarinvsn** [comment]
Hi Luke,

This is the log output from mongo-connector:
2015-07-14 16:45:26,145 [ERROR] mongo_connector.util:87 - Fatal Exception
2015-07-14 16:50:41,541 [ERROR] mongo_connector.util:87 - Fatal Exception
2015-07-14 16:50:57,749 [ERROR] mongo_connector.util:87 - Fatal Exception
2015-07-14 16:58:25,040 [ERROR] mongo_connector.util:87 - Fatal Exception
2015-07-14 17:12:37,960 [ERROR] mongo_connector.util:87 - Fatal Exception
2015-07-14 17:48:24,620 [ERROR] mongo_connector.util:87 - Fatal Exception

Each exception matches one update command.

To start mongo-connector I use either this:

    /mongo-connector --auto-commit-interval=1 -m localhost:27017 -t
    http://testingserver2:8983/solr/coreTransfers/ -d solr_doc_manager//
    /

or this:

    /mongo-connector --auto-commit-interval=1 -m localhost:27017 -t
    http://testingserver2:8983/solr/coreTransfers/ -n
    VSNBIStore.Transfers -d solr_doc_manager/

I use the -n option to connect only one connection of one database with 
the solr core. The problem occurs with both options.

Thanks for your help!

Best,
Raúl


El 14/07/2015 a las 20:01, Luke Lovett escribió:
> Hi Raul,
>
> Can you please provide the following:
> - Log output from mongo-connector
> - The command used to run mongo-connector
>
> Thanks!
>
> On Tue, Jul 14, 2015 at 9:17 AM, rmarinvsn <notifications@github.com> 
> wrote:
>
> > Hi,
> >
> > First of all, I think the idea of mongo-connector is just great, thanks
> > for invest your time on this.
> >
> > Now, I have a problem: mongo-connector shows an error when I try to 
> update
> > an existing document . I installed mongo-connector with pip, so I 
> guess I
> > have the latest version . When I insert or delete documents in Mongo,
> > mongo-connector works just fine, but when I try to update an existing
> > document, the command line window that is running mongo-connector shows:
> >
> > Exception in thread Thread-2:
> > Traceback (most recent call last):
> > File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
> > self.run()
> > File "C:\Python34\lib\site-packages\mongo_connector\util.py", line 
> 85, in
> > wrapped
> > func(*args, **kwargs)
> > File "C:\Python34\lib\site-packages\mongo_connector\oplog_manager.py",
> > line 263, in run
> > ns, timestamp)
> > File "C:\Python34\lib\site-packages\mongo_connector\util.py", line 
> 32, in
> > wrapped
> > return f(*args, **kwargs)
> > File
> > 
> "C:\Python34\lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py",
> > line 246, in update
> > doc.pop('ns')
> > KeyError: 'ns'
> >
> > I need to force a resynch (deleting oplog.timestamp and restarting) to
> > recover the system.
> >
> > What am I doing wrong?
> >
> > Best,
> > Raúl
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/10gen-labs/mongo-connector/issues/284>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/10gen-labs/mongo-connector/issues/284#issuecomment-121324497>.
>

-- 

*Raúl Marín Martínez*
Senior software developer
rmarin@vsn.es
Skype: rmarin_justedit

*VSN Alicante, R&D Office*
C/ Seis de Diciembre 5, entlo izq.
03550 San Juan de Alicante - Spain
Telf: (+34) 96 5993670 Ext. 209

www.vsn-tv.com <http://www.vsn-tv.com/> 	*Follow us!* Facebook 
<http://www.facebook.com/videostreamnetworks> Twitter 
<http://twitter.com/tapeless_tv> Linkedin 
<https://www.linkedin.com/company/924932?trk=tyah&trkInfo=tarId%3A1397554255492%2Ctas%3Avsn%2Cidx%3A1-1-1> 


*
VSN 
<http://www.vsn-tv.com/signmail/?dpt=development&utm_source=Desarrollo&utm_medium=Email&utm_campaign=Firma%20>*

*<http://www.vsn-tv.com/signmail/?dpt=development&utm_source=Desarrollo&utm_medium=Email&utm_campaign=Firma%20> 


<http://www.vsn-tv.com/signmail/?dpt=development&utm_source=Desarrollo&utm_medium=Email&utm_campaign=Firma%20>Protection 
data Policy & Disclaimer | Política de Protección de Datos y Advertencia 
legal <http://www.vsn-tv.com/signmail/?legal=TRUE>

*

**Comment by llvtt** [comment]
One more question: do you have an `ns` field defined in your schema.xml? This page gives some information on setting up schema: https://github.com/10gen-labs/mongo-connector/wiki/Usage-with-Solr#set-up-your-schema. It looks like this problem could be caused by mongo-connector removing a field it assumes to be there (it puts it there in the first place, but it would be removed if it's not in the schema).

**Comment by rmarinvsn** [comment]
Hi Luke,

No, I don't have any "ns" field. I send you my schema.xml. I'll try to 
check if there is any difference between the schema and the objects tham 
I'm using.

Best,
Raúl



El 16/07/2015 a las 23:37, Luke Lovett escribió:
>
> One more question: do you have an |ns| field defined in your 
> schema.xml? This page gives some information on setting up schema: 
> https://github.com/10gen-labs/mongo-connector/wiki/Usage-with-Solr#set-up-your-schema. 
> It looks like this problem could be caused by mongo-connector removing 
> a field it assumes to be there (it puts it there in the first place, 
> but it would be removed if it's not in the schema).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/10gen-labs/mongo-connector/issues/284#issuecomment-122108799>.
>

-- 

*Raúl Marín Martínez*
Senior software developer
rmarin@vsn.es
Skype: rmarin_justedit

*VSN Alicante, R&D Office*
C/ Seis de Diciembre 5, entlo izq.
03550 San Juan de Alicante - Spain
Telf: (+34) 96 5993670 Ext. 209

www.vsn-tv.com <http://www.vsn-tv.com/> 	*Follow us!* Facebook 
<http://www.facebook.com/videostreamnetworks> Twitter 
<http://twitter.com/tapeless_tv> Linkedin 
<https://www.linkedin.com/company/924932?trk=tyah&trkInfo=tarId%3A1397554255492%2Ctas%3Avsn%2Cidx%3A1-1-1> 


*
VSN 
<http://www.vsn-tv.com/signmail/?dpt=development&utm_source=Desarrollo&utm_medium=Email&utm_campaign=Firma%20>*

*<http://www.vsn-tv.com/signmail/?dpt=development&utm_source=Desarrollo&utm_medium=Email&utm_campaign=Firma%20> 


<http://www.vsn-tv.com/signmail/?dpt=development&utm_source=Desarrollo&utm_medium=Email&utm_campaign=Firma%20>Protection 
data Policy & Disclaimer | Política de Protección de Datos y Advertencia 
legal <http://www.vsn-tv.com/signmail/?legal=TRUE>

*

**Comment by rmarinvsn** [comment]
Hi,

There were some fields marked as "float" in the schema where Mongo uses 
"double". I've tried to change that but the problem is still there. 
Appart from that I cannot see more differences, the schema matches the 
object I store in MongoDB.

Best,
Raúl

El 16/07/2015 a las 23:37, Luke Lovett escribió:
>
> One more question: do you have an |ns| field defined in your 
> schema.xml? This page gives some information on setting up schema: 
> https://github.com/10gen-labs/mongo-connector/wiki/Usage-with-Solr#set-up-your-schema. 
> It looks like this problem could be caused by mongo-connector removing 
> a field it assumes to be there (it puts it there in the first place, 
> but it would be removed if it's not in the schema).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/10gen-labs/mongo-connector/issues/284#issuecomment-122108799>.
>

-- 

*Raúl Marín Martínez*
Senior software developer
rmarin@vsn.es
Skype: rmarin_justedit

*VSN Alicante, R&D Office*
C/ Seis de Diciembre 5, entlo izq.
03550 San Juan de Alicante - Spain
Telf: (+34) 96 5993670 Ext. 209

www.vsn-tv.com <http://www.vsn-tv.com/> 	*Follow us!* Facebook 
<http://www.facebook.com/videostreamnetworks> Twitter 
<http://twitter.com/tapeless_tv> Linkedin 
<https://www.linkedin.com/company/924932?trk=tyah&trkInfo=tarId%3A1397554255492%2Ctas%3Avsn%2Cidx%3A1-1-1> 


*
VSN 
<http://www.vsn-tv.com/signmail/?dpt=development&utm_source=Desarrollo&utm_medium=Email&utm_campaign=Firma%20>*

*<http://www.vsn-tv.com/signmail/?dpt=development&utm_source=Desarrollo&utm_medium=Email&utm_campaign=Firma%20> 


<http://www.vsn-tv.com/signmail/?dpt=development&utm_source=Desarrollo&utm_medium=Email&utm_campaign=Firma%20>Protection 
data Policy & Disclaimer | Política de Protección de Datos y Advertencia 
legal <http://www.vsn-tv.com/signmail/?legal=TRUE>

*

**Comment by llvtt** [comment]
Hi Raul,

You need to add a couple fields to your schema.xml to store metadata used
by mongo-connector. Please see this section of the "Usage with Solr" wiki
page for information on what needs to be added:
https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20Solr#set-up-your-schema.
After you set up these fields, reload the core and re-index the documents
from MongoDB:
https://github.com/10gen-labs/mongo-connector/wiki/FAQ#how-do-i-re-sync-all-data-from-scratch

**Comment by rmarinvsn** [comment]
Hi Luke, 

That was the problem. I'm sorry I forgot that step. It works perfectly fine know.

Thank you very much, I really appreciate it,
