### ISSUE TITLE
oplog.timestamp becomes empty when ConnectionTimeout (Elasticsearch)

### ISSUE THREAD

**Issue by methuz** [10gen-labs/mongo-connector#294]
Hi, I'm having a problem here. I'm trying to sync my 300GB/28 replica set using 3 machines, 8 mongo_connector per each machine to Elasticsearch. My first problem is it's never been done because of this error

```
2015-07-27 09:51:50,427 [CRITICAL] mongo_connector.oplog_manager:543 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 495, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 479, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
    for ok, resp in responses:
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 124, in streaming_bulk
    raise e
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'es2-client-01', port=1030): Read timed out. (read timeout=10))
2015-07-27 09:51:50,428 [ERROR] mongo_connector.oplog_manager:551 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient([u'v2mgrs0x1:1030', u'v2mgrs0x0:1030']), u'local'), u'oplog.rs')
2015-07-27 09:51:50,786 [ERROR] mongo_connector.connector:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 140391047177984)> unexpectedly stopped! Shutting down
```
I think this problem is because Elasticsearch Cluster. But my problem with mongo_connector is `oplog.timestamp` file turn to be empty. (It was not empty at the very first hour).

This is my config file.
```
{ "mainAddress": "", "oplogFile": "/var/log/mongo-connector/oplog0.timestamp",
    "noDump": false,
    "verbosity": 0,
    "continueOnError": false,

    "logging": {
        "type": "file",
        "filename": "/var/log/mongo-connector/mongo-connector0.log",
        "rotationWhen": "D",
        "rotationInterval": 1,
        "rotationBackups": 10
    },

    "authentication": {
        "adminUsername": "",
        "password": ""
    },

    "fields": ["myfields"],

    "namespaces": {
        "mapping": {
            "": ""
        }
    },

    "docManagers": [
        {
            "docManager": "elastic_doc_manager",
            "targetURL": ",
            "__bulkSize": 1000,
            "__uniqueKey": "_id",
            "__autoCommitInterval": null
        }
    ]
}
```

**Comment by llvtt** [comment]
I'm not sure that I understand the situation. It looks like there was a ConnectionTimeout while dumping the collection to Elasticsearch (this happens before tailing the oplog). Mongo Connector shouldn't write anything to the oplog progress file in this case, since saving time timestamp isn't useful without having successfully dumped collections from MongoDB into Elasticseaarch first. I would expect the timestamp file to be empty.

Was this timestamp file from a previous run of mongo-connector?

There should be no writes to the oplog progress file while the collection dump is happening, so the instance of mongo-connector that had the ConnectionTimeout shouldn't ever have written to the file. However, since mongo-connector failed during the collection dump, it does truncate the oplog progress file, indicating that another collection dump has to be attempted.

**Comment by methuz** [comment]
Ok, So we cannot recover if error occur before tailing oplog right? Is it possible to do so?

**Comment by llvtt** [comment]
That is correct; errors encountered before tailing the oplog are always
fatal. There is a "--continue-on-error" flag that ignores errors during the
collection dump, but this can cause errors in the future when attempting to
apply the oplog. Use it with caution!

**Comment by methuz** [comment]
Thanks. One more question please, How to check which stage is my mongo-connector (Dumping or Oplog tailling)?

**Comment by llvtt** [comment]
If you turn on verbose logging (-v), you'll see a log message like
"OplogThread: about to process new oplog entries" in the log file. This
indicates that mongo-connector is beginning to process the oplog and that
the collection dump has finished.

On Wed, Jul 29, 2015 at 1:58 AM, Methuz Kaewsaikao <notifications@github.com

**Comment by methuz** [comment]
Thanks!

**Comment by llvtt** [comment]
No problem

**Comment by Khsaf** [comment]
@llvtt I have a question related to this issue. Is there any way to resume collection dump process from the point before failure (timeout)?

I am indexing MongoDB collection using Solr and finding it very hard to complete the data dump part successfully. The collection is huge (over 100 million records / over 300GB) and the data dump takes days. 

I wish there is a way to resume the data dump from the point of failure. Especially that the failure is as simple as connection timeout!
