### ISSUE TITLE
Config.json parsing is failing

### ISSUE THREAD

**Issue by ussrinivas** [10gen-labs/mongo-connector#297]
Hi,

   Here is my config.json while I am trying to start mongo-connector with this config file as follows along with logs. Is there anything wrong with this config?

`mongo-connector -c config.json`

*{
    "mainAddress": "localhost:27017",
    "docManagers.0.docManager": "solr_doc_manager",
    "docManagers.0.autoCommitInterval": 0,
    "docManagers.0.targetURL": "http://localhost:8983/solr/sample",
    "namespacesi.include": "sample.Sku",
    "verbosity": 3,
    "continueOnError": true,
    "logging.filename": "/var/log/mongo-connector.log"
}*

I am seeing following warnings

*WARNING:root:Unrecognized option: docManagers.0.autoCommitInterval
WARNING:root:Unrecognized option: docManagers.0.docManager
WARNING:root:Unrecognized option: docManagers.0.targetURL
WARNING:root:Unrecognized option: namespacesi.include
WARNING:root:Unrecognized option: logging.filename
Logging to mongo-connector.log.
INFO:mongo_connector.connector:Beginning Mongo Connector
WARNING:mongo_connector.connector:No doc managers specified, using simulator.*

**Comment by llvtt** [comment]
1.  "docManagers" should be a list of JSON objects. See this example:
https://github.com/10gen-labs/mongo-connector/blob/master/config.json#L48-L56
.
2. "logging" is also a JSON object:
https://github.com/10gen-labs/mongo-connector/blob/master/config.json#L12-L21

**Comment by ussrinivas** [comment]
Thanks Luke it is working now. Closing the issue
