### ISSUE TITLE
Install in offline server has error: Could not find suitable distribution for Requirement.parse('elasticsearch>=1.2')

### ISSUE THREAD

**Issue by tupn2002** [10gen-labs/mongo-connector#301]
Hello,

I try install in an offline server so many time, but it always show the error:
rocessing dependencies for mongo-connector==2.1
Searching for elasticsearch>=1.2
Reading http://pypi.python.org/simple/elasticsearch/
Download error: [Errno -2] Name or service not known -- Some packages may not be found!
Reading http://pypi.python.org/simple/elasticsearch/
Download error: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'elasticsearch' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
Download error: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or download links found for elasticsearch>=1.2
error: Could not find suitable distribution for Requirement.parse('elasticsearch>=1.2')

My offline server is RHEL 6.
I already installed elastic 1.7.1

Step to reproduce:
Download zip file from git.
Copy to server.
Unzip the zip file.
Run: python setup.py install.
Could anyone please show me what is wrong in my steps?
Thank you.
Regards,
Tu

**Comment by llvtt** [comment]
You need an internet connection in order to automatically install all the
dependencies for mongo-connector with 'pip'.

**Comment by tupn2002** [comment]
Thank you.
I have some security reasons, so I could not have internet connection in the server.
I already downloaded all related packages and install them manually.
Regards,
Tu.
