### ISSUE TITLE
Steps needed to install Mongo Connector offline?

### ISSUE THREAD

**Issue by howardkhl** [10gen-labs/mongo-connector#320]
I'd need to install Mongo Connector on a server without http. What are the steps needed to achieve this? Thanks.

**Comment by llvtt** [comment]
mongo-connector is a python package. Searching around for "install python package offline" could be useful: http://stackoverflow.com/questions/11091623/python-packages-offline-installation

**Comment by howardkhl** [comment]
Reference for those stumbled in this thread.

To make Mongo Connector available offline:

    pip install --download /path/to/some/dir mongo-connector

Then, on the offline server:

    pip install --no-index --find-links /path/to/some/dir mongo-connector

Pip is available in standard Python build. However, if running CentOS 6.x or any Linux distro with Python 2.6.x, you might have an outdated `pip 1.3.1` (latest is `pip is 7.x.x`, install/upgrade [here](https://pip.pypa.io/en/latest/installing.html)). With pip 1.3.1, it does not use Wheel, but you can still grab all dependencies with `--download` option. Make sure to run the commands several times `pip install --download /path/to/some/dir mongo-connector` (probably 2~3 times so it will grab all the needed dependencies). After that you can `tar zcvf mongo-connector.tar.gz /path/to/grabbed/dependencies` and transfer it to offline server. This is not an issue with `pip 7.x.x` as it uses Wheel.

**Comment by llvtt** [comment]
Thanks for the instructions, @howardkhl. I added this to the [FAQ](https://github.com/mongodb-labs/mongo-connector/wiki/FAQ#how-can-i-install-mongo-connector-without-internet-access).
